# Generated by Django 3.0.7 on 2021-11-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211129_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='equipment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
